spring:
  application:
    name: tilimanager
  profiles:
    active: prod


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secreto: FernandoPorrinoGuapo2704PorfavorUn10Gracias