INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Pau');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Jalel');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Raphael');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'MrPopo');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'MrGay');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'John Marston');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Arthur Morgan');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Diego');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Messi');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'CurriculumVitae');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Gustin');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Adrian');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Justin');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Santiago');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Pepe');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Deulofue');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Tadi');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'safu');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'Jose');
INSERT INTO player (attack, defense, rating, name) values(88,82,85, 'proba');